# -*- coding: utf-8 -*-
"""MRI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqaP4M2SNqcVcWuH1rcclWfZOLma46fe
"""

# ==========================================
# PART 1 : EfficientNet + 幾何保留策略
# ==========================================
!pip install roboflow opencv-python matplotlib scikit-learn tensorflow seaborn

import os
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras import mixed_precision
from sklearn.utils import class_weight
from roboflow import Roboflow

try:
    from google.colab import files
except ImportError:
    pass

# 0. 清理舊模型與環境
tf.keras.backend.clear_session()
if os.path.exists('my_mri_model.h5'):
    os.remove('my_mri_model.h5')

# 開啟混合精度加速 (報告中提到的 Mixed Precision)
mixed_precision.set_global_policy('mixed_float16')

# 1. 下載資料
rf = Roboflow(api_key="Fejkqw1NB22U2OhV41Ph")
project = rf.workspace("mri-l4mg5").project("mri-brain-tumor-nxio6")
version = project.version(2)
dataset = version.download("folder")

dataset_path = dataset.location
train_dir = os.path.join(dataset_path, "train")
valid_dir = os.path.join(dataset_path, "valid")

# 2. 影像前處理 (報告中提到的 CLAHE 技術)
def report_preprocessing(img):
    img = img.astype('uint8')
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    # CLAHE: 限制對比度自適應直方圖均衡化
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    cl = clahe.apply(l)
    limg = cv2.merge((cl,a,b))
    img_enhanced = cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)
    return img_enhanced.astype('float32')

# 3. 資料生成 (⚠️ 關鍵修正：幾何保留策略)
# 對應報告：修正了過度旋轉導致位置特徵遺失的問題
BATCH_SIZE = 16
IMG_SIZE = (224, 224)

train_datagen = ImageDataGenerator(
    preprocessing_function=report_preprocessing,
    # 🔥 修改點：將旋轉與位移降至極低，僅模擬些微誤差
    rotation_range=2,        # 從 20 改為 2 (幾乎不旋轉)
    width_shift_range=0.02,  # 從 0.1 改為 0.02
    height_shift_range=0.02, # 從 0.1 改為 0.02
    zoom_range=0.02,         # 降低縮放幅度
    brightness_range=[0.8, 1.2], # 保留亮度變化以適應不同成像條件
    horizontal_flip=True,    # 左右翻轉是解剖學上合理的 (人腦對稱)
    fill_mode='nearest',
    rescale=1./255
)

valid_datagen = ImageDataGenerator(
    preprocessing_function=report_preprocessing,
    rescale=1./255
)

train_generator = train_datagen.flow_from_directory(
    train_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical')

valid_generator = valid_datagen.flow_from_directory(
    valid_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical')

# 4. 權重計算 (報告中提到的類別不平衡處理)
original_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_generator.classes),
    y=train_generator.classes
)
class_weights_dict = dict(enumerate(original_weights))

# 針對 Glioma 給予權重加成 (解決誤判問題)
indices = train_generator.class_indices
glioma_idx = indices.get('glioma_tumor')
if glioma_idx is not None:
    class_weights_dict[glioma_idx] *= 2.0
    print(f"🔥 實施 Glioma 權重加強策略: {class_weights_dict}")

# 5. 建立模型 (報告中提到的 EfficientNetB0 架構)
# include_top=False: 移除原分類層
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# 🔥 全模型解鎖 (Full Unfreeze)：適應 MRI 特殊紋理
base_model.trainable = True

x = base_model.output
x = GlobalAveragePooling2D()(x) # 報告提到的 GAP 層

# 報告提到的分類頭設計 (Dense + BN + Dropout)
x = BatchNormalization()(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)

x = BatchNormalization()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.4)(x)

predictions = Dense(train_generator.num_classes, activation='softmax', dtype='float32')(x)

model = Model(inputs=base_model.input, outputs=predictions)

# 6. 編譯設定 (報告中提到的極低學習率策略)
model.compile(optimizer=Adam(learning_rate=1e-5), # 1e-5 = 0.00001
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 7. 訓練設定
checkpoint = ModelCheckpoint('my_mri_model.h5',
                             monitor='val_accuracy',
                             save_best_only=True,
                             verbose=1)

early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7)

print("🚀 啟動 EfficientNet 全域微調 (幾何保留模式)...")

history = model.fit(
    train_generator,
    epochs=40,
    validation_data=valid_generator,
    class_weight=class_weights_dict,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

print("\n✅ 訓練完成！模型已符合報告所述之幾何保留策略。")
try:
    files.download('my_mri_model.h5')
except:
    pass

# ==========================================
# PART 2 (測試)
# ==========================================
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from google.colab import files
import math

# 1. 定義影像前處理 (必須與訓練時一模一樣)
def report_preprocessing(img):
    img = img.astype('uint8')
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    # 這裡維持 2.0，因為這是您剛才 EfficientNet 用的參數
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    cl = clahe.apply(l)
    limg = cv2.merge((cl,a,b))
    img_enhanced = cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)
    return img_enhanced.astype('float32')

# 2. 載入模型
print("🔄 正在讀取模型 'my_mri_model.h5' ...")

if not os.path.exists('my_mri_model.h5'):
    print("❌ 錯誤：找不到模型檔案！請確認 Part 1 是否已跑完並存檔。")
else:
    # 載入模型 (需傳入自定義函數)
    model = load_model('my_mri_model.h5', custom_objects={'report_preprocessing': report_preprocessing})
    print("✅ 模型載入成功！")

    # 定義類別 (Roboflow 預設排序)
    class_labels = ['glioma', 'meningioma', 'notumor', 'pituitary']

    print("\n" + "="*40)
    print("【 步驟 1 】請上傳一批「同一種類別」的照片")
    print("="*40)
    uploaded = files.upload()

    # 如果有上傳檔案
    if len(uploaded) > 0:
        num_files = len(uploaded)

        # 3. 詢問使用者正確答案
        print("\n" + "="*40)
        print("【 步驟 2 】請告訴我這批照片的正確答案是誰？")
        print(f" 0 : {class_labels[0]} (神經膠質瘤)")
        print(f" 1 : {class_labels[1]} (腦膜瘤)")
        print(f" 2 : {class_labels[2]} (無腫瘤)")
        print(f" 3 : {class_labels[3]} (垂體瘤)")
        print("="*40)

        while True:
            try:
                true_idx = int(input(f"請輸入正確類別的編號 (0-3): "))
                if 0 <= true_idx <= 3:
                    true_label_name = class_labels[true_idx]
                    break
                else:
                    print("⚠️ 請輸入 0 到 3 之間的數字！")
            except ValueError:
                print("⚠️ 請輸入數字！")

        print(f"\n🚀 收到！正在以「{true_label_name}」為標準進行批次評分...\n")

        # 4. 開始批次預測
        correct_count = 0
        cols = 3
        rows = math.ceil(num_files / cols)
        plt.figure(figsize=(15, 5 * rows))

        for i, fn in enumerate(uploaded.keys()):
            # A. 讀取
            ax = plt.subplot(rows, cols, i + 1)
            img = load_img(fn, target_size=(224, 224))

            # B. 預處理與預測
            x = img_to_array(img)
            x = report_preprocessing(x)
            x = np.expand_dims(x, axis=0)
            x = x / 255.0 # EfficientNet 訓練時若有 rescale，這裡也要有

            pred = model.predict(x, verbose=0)
            result_idx = np.argmax(pred[0])
            result_label = class_labels[result_idx]
            confidence = np.max(pred[0]) * 100

            # C. 判斷對錯
            is_correct = (result_idx == true_idx)
            if is_correct:
                correct_count += 1
                status_color = 'green'
                status_icon = '✅'
            else:
                status_color = 'red'
                status_icon = '❌'

            # D. 繪圖與標示
            plt.imshow(img)
            plt.axis('off')

            # 標題顯示：預測結果 (信心度)
            # 如果錯了，會括號顯示正確答案
            if is_correct:
                title_text = f"{status_icon} Pred: {result_label}\nConf: {confidence:.1f}%"
            else:
                title_text = f"{status_icon} Pred: {result_label}\n(True: {true_label_name})\nConf: {confidence:.1f}%"

            plt.title(title_text, color=status_color, fontsize=12, fontweight='bold')

        plt.tight_layout()
        plt.show()

        # 5. 最終結算報告
        accuracy = (correct_count / num_files) * 100
        print("\n" + "="*40)
        print(f"📊 測試報告 (Ground Truth: {true_label_name})")
        print("-" * 40)
        print(f"總張數    : {num_files}")
        print(f"答對張數  : {correct_count}")
        print(f"答錯張數  : {num_files - correct_count}")
        print("-" * 40)
        print(f"🏆 本次準確率 : {accuracy:.2f}%")
        print("="*40)

    else:
        print("⚠️ 你沒有選擇任何檔案喔！")